# .github/workflows/ci.yml
name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.png'
      - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pytest ruff

      - run: ruff check .

      - run: pytest; status=$?; if [ $status -eq 0 ] || [$status -eq 5]; then exit 0; else exit $status; fi